version: '3.8'

services:
  glyphforge:
    build: .
    container_name: glyphforge-app
    ports:
      - "40001:3001"
    volumes:
      # Modify to your actual path
      # Windows example: D:/Glyphforge-data:/datas
      # Linux/Mac example: /home/user/glyphforge-data:/datas
      # NAS example: /var/services/homes/dannyho/deployment_datas/Glyphforge:/datas
      - /var/services/homes/dannyho/deployment_datas/Glyphforge:/datas
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
